## ---------------------------------------------------------------------------
##
## File: dockerfile for Inference Demo
##
## Created by Zhijin Li
## E-mail:   <zhijinl@nvidia.com>
##
## Started on  Mon Feb 26 14:35:32 2024 Zhijin Li
## Last update Mon Feb 26 22:15:57 2024 Zhijin Li
## ---------------------------------------------------------------------------


FROM nvcr.io/nvidia/pytorch:24.01-py3

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install timm colored
RUN pip install monai[pillow]
